version: '3'

services:
  activemq:
    container_name: activemq
    image: symptoma/activemq:latest
    ports:
      - 8161:8161
      - 61616:61616
    environment:
      ACTIVEMQ_DISALLOW_WEBCONSOLE: false
      ACTIVEMQ_USERNAME: admin
      ACTIVEMQ_PASSWORD: admin
      ACTIVEMQ_WEBADMIN_USERNAME: webadmin
      ACTIVEMQ_WEBADMIN_PASSWORD: webadmin